const fs = require('fs');
const path = require('path');

const imgDir = 'Img';
const dirs = fs.readdirSync(imgDir, { withFileTypes: true }).filter(d => d.isDirectory()).map(d => d.name);
const folderPhotosMap = {};
dirs.forEach(d => {
  const files = fs.readdirSync(path.join(imgDir, d));
  const numbered = files.filter(f => /^\d{1,3}\.(jpg|jpeg|png|webp)$/i.test(f)).sort((a,b) => parseInt(a,10) - parseInt(b,10));
  folderPhotosMap[d] = numbered.map(f => `/Img/${encodeURIComponent(d)}/${f}`);
});

const places = [
  {
    id: 1,
    name: "ปราสาททองกาญจนาภิเษก (ปราสาททองคำ)",
    altName: "",
    shortName: "ปราสาททองคำ",
    zone: "wat-mai",
    category: "palace",
    highlight: true,
    description: "ปราสาทสีทองอร่าม 3 ชั้น ก่อสร้างด้วยสถาปัตยกรรมไทยประยุกต์วิจิตรงดงาม ยอดปราสาทประดับทองคำแท้ สร้างขึ้นเพื่อถวายเป็นพระราชกุศลแด่ในหลวงรัชกาลที่ 9 ในวโรกาสครองราชย์ครบ 50 ปี",
    openingHours: {
      allDay: { open: "08:30", close: "16:00" },
      note: "เปิดให้เข้าชมทุกวัน กรุณาถอดรองเท้าและแต่งกายสุภาพ",
    },
    gps: { lat: 15.329376018112319, lng: 100.06931802853471 },
    tips: "ควรถอดหมวกและแว่นตาดำก่อนเข้าชม มีจุดชมวิวรอบปราสาทชั้นบน",
    photos: folderPhotosMap["ปราสาททองกาญจนาภิเษก (ปราสาททองคำ)"] || [],
  },
  {
    id: 2,
    name: "พิพิธภัณฑ์สมบัติพ่อให้",
    altName: "",
    shortName: "สมบัติพ่อให้",
    zone: "wat-mai",
    category: "museum",
    highlight: true,
    description: "พิพิธภัณฑ์รวบรวมและจัดแสดงอัฐบริขาร วัตถุมงคล ของใช้ส่วนตัว และสิ่งของล้ำค่าที่พระราชพรหมยาน (หลวงพ่อฤาษีลิงดำ) ได้มอบไว้เป็นมรดกธรรมแก่ศิษยานุศิษย์",
    openingHours: {
      morning: { open: "09:00", close: "11:30" },
      afternoon: { open: "13:30", close: "16:00" },
      note: "เปิดเฉพาะวันเสาร์-อาทิตย์ และวันหยุดนักขัตฤกษ์",
    },
    gps: { lat: 15.331315178361331, lng: 100.0689571785189 },
    tips: "แนะนำให้มาในวันเสาร์-อาทิตย์เพื่อเข้าชมภายใน ห้ามถ่ายภาพในบางโซนจัดแสดง",
    photos: folderPhotosMap["พิพิธภัณฑ์สมบัติพ่อให้"] || [],
  },
  {
    id: 3,
    name: "พระยืน 30 ศอก (หลวงพ่อเงินไหลมาเทมา)",
    altName: "",
    shortName: "พระยืน 30 ศอก",
    zone: "wat-mai",
    category: "buddha",
    highlight: true,
    description: "พระพุทธรูปปางอุ้มบาตร สูงตระหง่าน 30 ศอก (ประมาณ 15 เมตร) ปิดทองคำแท้ทั้งองค์ สาธุชนนิยมมากราบไหว้สวดคาถาเงินล้านเพื่อขอพรโชคลาภ ความสำเร็จ และความคล่องตัวทางการเงิน",
    openingHours: {
      allDay: { open: "08:00", close: "17:00" },
      note: "ลานกลางแจ้ง เปิดให้กราบไหว้ทุกวัน",
    },
    gps: { lat: 15.33218859674792, lng: 100.06914476029037 },
    tips: "นิยมสวดคาถาเงินล้าน 9 จบ หน้าองค์พระเพื่อความเป็นสิริมงคล",
    photos: folderPhotosMap["พระยืน 30 ศอก (หลวงพ่อเงินไหลมาเทมา)"] || [],
  },
  {
    id: 4,
    name: "วิหารสมเด็จองค์ปฐม",
    altName: "",
    shortName: "สมเด็จองค์ปฐม",
    zone: "wat-mai",
    category: "vihara",
    highlight: true,
    description: "วิหารประดิษฐานพระพุทธรูปสมเด็จองค์ปฐม (พระสัมมาสัมพุทธเจ้าพระองค์แรกในจักรวาล) หน้าตัก 4 ศอก หล่อด้วยทองสำริดปิดทองคำประดับเพชร ภายในวิหารตกแต่งด้วยกระจกเงาสะท้อนแสงแวววาว",
    openingHours: {
      morning: { open: "09:00", close: "10:30" },
      afternoon: { open: "13:00", close: "16:00" },
      note: "เปิดทุกวันตามรอบเวลา กรุณาถอดรองเท้าก่อนเข้า",
    },
    gps: { lat: 15.332439790276979, lng: 100.06964298699376 },
    tips: "เชื่อกันว่าอานิสงส์การบูชาสมเด็จองค์ปฐมตัดเวรกรรมและนำพาชีวิตสู่ความเจริญรุ่งเรืองสูงสุด",
    photos: folderPhotosMap["วิหารสมเด็จองค์ปฐม"] || [],
  },
  {
    id: 5,
    name: "ลาน 25 ไร่",
    altName: "",
    shortName: "ลาน 25 ไร่",
    zone: "wat-mai",
    category: "facility",
    highlight: false,
    description: "ลานอเนกประสงค์กลางแจ้งและจุดจอดรถยนต์ขนาดใหญ่ของวัด รองรับรถบัส รถตู้ และรถยนต์ส่วนบุคคลของสาธุชนในช่วงงานพิธีบุญใหญ่",
    openingHours: {
      allDay: { open: "06:00", close: "18:00" },
      note: "เปิดบริการทุกวัน มีห้องสุขาและจุดพักคอย",
    },
    gps: { lat: 15.330420128417968, lng: 100.0701856946274 },
    tips: "มีบริการรถรางรับส่งไปยังจุดสำคัญต่างๆ ในช่วงวันหยุดหรือวันมีงานเทศกาล",
    photos: folderPhotosMap["ลาน 25 ไร่"] || [],
  },
  {
    id: 6,
    name: "วิหารพระวิสุทธิเทพ",
    altName: "",
    shortName: "วิหารพระวิสุทธิเทพ",
    zone: "wat-mai",
    category: "vihara",
    highlight: true,
    description: "วิหารประดิษฐานพระวิสุทธิเทพบนพระแท่นแก้ว ศิลปกรรมอันประณีตงดงามยิ่ง ณ แดนพระนิพพาน เป็นที่เคารพสักการะของพุทธศาสนิกชนสายพระกรรมฐาน",
    openingHours: {
      allDay: { open: "09:00", close: "16:00" },
      note: "เปิดให้สักการะทุกวัน กรุณาแต่งกายสุภาพ",
    },
    gps: { lat: 15.33265, lng: 100.06925 },
    tips: "เป็นสถานที่เงียบสงบ เหมาะสำหรับกราบไหว้และเจริญสมาธิภาวนา",
    photos: folderPhotosMap["วิหารพระวิสุทธิเทพ"] || [],
  },
  {
    id: 7,
    name: "ตึกขาว",
    altName: "",
    shortName: "ตึกขาว",
    zone: "wat-mai",
    category: "facility",
    highlight: false,
    description: "อาคารตึกขาวสองชั้นสไตล์เรียบง่าย ใช้สำหรับกิจกรรมสงฆ์ เป็นจุดอำนวยการและประสานงานภายในวัดฝั่งใหม่",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดตามเวลาราชการ/เวลาทำการวัด",
    },
    gps: { lat: 15.33051839941299, lng: 100.07101713714478 },
    tips: null,
    photos: folderPhotosMap["ตึกขาว"] || [],
  },
  {
    id: 8,
    name: "มณฑปพระศรีอาริยเมตไตรย",
    altName: "",
    shortName: "พระศรีอาริยเมตไตรย",
    zone: "wat-mai",
    category: "vihara",
    highlight: false,
    description: "มณฑปทรงจัตุรมุขยอดปรางค์ ประดิษฐานรูปหล่อพระศรีอาริยเมตไตรย พระอนาคตพุทธเจ้าที่จะมาตรัสรู้ในกัปป์ต่อไป",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดให้กราบไหว้ทุกวัน",
    },
    gps: { lat: 15.332046931531451, lng: 100.06996332344809 },
    tips: "ตั้งอยู่ใกล้กับวิหารสมเด็จองค์ปฐม สามารถเดินเชื่อมถึงกันได้สะดวก",
    photos: folderPhotosMap["มณฑปพระศรีอาริยเมตไตรย"] || [],
  },
  {
    id: 9,
    name: "สวนสมเด็จฯ",
    altName: "",
    shortName: "สวนสมเด็จฯ",
    zone: "wat-mai",
    category: "facility",
    highlight: false,
    description: "สวนสาธารณะร่มรื่น สระน้ำ และพื้นที่พักผ่อนหย่อนใจของวัด เหมาะสำหรับเดินรับลม นั่งสมาธิ และพักผ่อนตามอัธยาศัย",
    openingHours: {
      allDay: { open: "07:00", close: "17:30" },
      note: "เปิดทุกวัน บรรยากาศร่มรื่นริมสระน้ำ",
    },
    gps: { lat: 15.333374917830827, lng: 100.07175844104083 },
    tips: "จุดพักผ่อนร่มรื่นระหว่างเดินชมฝั่งวัดใหม่",
    photos: folderPhotosMap["สวนสมเด็จฯ"] || [],
  },
  {
    id: 10,
    name: "ตึกพระเถระ",
    altName: "",
    shortName: "ตึกพระเถระ",
    zone: "wat-mai",
    category: "facility",
    highlight: false,
    description: "อาคารตึกสำหรับรับรองพระมหาเถระและพระภิกษุสงฆ์ที่เดินทางมาปฏิบัติศาสนกิจ ณ วัดท่าซุง",
    openingHours: {
      allDay: { open: "08:00", close: "16:30" },
      note: "เขตสังฆาวาส กรุณาสำรวมกิริยา",
    },
    gps: { lat: 15.333949251970875, lng: 100.07246080408117 },
    tips: null,
    photos: folderPhotosMap["ตึกพระเถระ"] || [],
  },
  {
    id: 11,
    name: "ร้านอิ่มบุญ (ครัวร้อยเมตร)",
    altName: "",
    shortName: "ร้านอิ่มบุญ",
    zone: "facility",
    category: "facility",
    highlight: false,
    description: "ร้านอาหารและเครื่องดื่มบริการแก่สาธุชนและนักท่องเที่ยว บริเวณข้างวิหารแก้ว 100 เมตร สะดวก สะอาด ราคาย่อมเยา",
    openingHours: {
      allDay: { open: "07:30", close: "16:00" },
      note: "เปิดบริการทุกวัน มีอาหารปรุงสุกสะอาดและเครื่องดื่ม",
    },
    gps: { lat: 15.33215, lng: 100.0729 },
    tips: "จุดแวะรับประทานอาหารกลางวันใกล้กับวิหารแก้ว 100 เมตร",
    photos: folderPhotosMap["ร้านอิ่มบุญ (ครัวร้อยเมตร)"] || [],
  },
  {
    id: 12,
    name: "วิหารแก้ว 100 เมตร",
    altName: "",
    shortName: "วิหารแก้ว 100 เมตร",
    zone: "wat-mai",
    category: "vihara",
    highlight: true,
    description: "มหาวิหารความยาว 100 เมตร เสาทุกต้นประดับด้วยโมเสกกระจกเงาสะท้อนแสงแวววาวดุจวิมานแก้วบนสวรรค์ เป็นที่ประดิษฐานพระสรีระสังขารของหลวงพ่อฤาษีลิงดำในโลงแก้ว และพระพุทธชินราชจำลอง",
    openingHours: {
      morning: { open: "09:00", close: "11:45" },
      afternoon: { open: "14:00", close: "16:00" },
      note: "เปิด 2 รอบทุกวัน | ติดต่อฝึกมโนมยิทธิ เวลา 11:00 - 11:30 น.",
    },
    gps: { lat: 15.332416129080686, lng: 100.072513066472 },
    tips: "ไฮไลต์สำคัญที่สุดของวัดท่าซุง ควรกะเวลาให้ตรงกับรอบเปิด 09:00-11:45 หรือ 14:00-16:00 น.",
    photos: folderPhotosMap["วิหารแก้ว 100 เมตร"] || [],
  },
  {
    id: 13,
    name: "Tha Sung Coffee (กาแฟท่าซุง)",
    altName: "",
    shortName: "กาแฟท่าซุง",
    zone: "facility",
    category: "facility",
    highlight: false,
    description: "ร้านกาแฟและเครื่องดื่มบรรยากาศร่มรื่นของวัดท่าซุง บริการเครื่องดื่มเย็น ชา กาแฟ เพื่อความสดชื่นแก่ผู้มาเยือน",
    openingHours: {
      allDay: { open: "08:00", close: "16:30" },
      note: "เปิดบริการทุกวัน",
    },
    gps: { lat: 15.33315, lng: 100.0736 },
    tips: "จุดพักผ่อนดื่มกาแฟและเครื่องดื่มเย็นๆ หลังเดินทางไหว้พระ",
    photos: folderPhotosMap["Tha Sung Coffee (กาแฟท่าซุง)"] || [],
  },
  {
    id: 14,
    name: "ร้านค้าสวัสดิการ",
    altName: "",
    shortName: "ร้านค้าสวัสดิการ",
    zone: "facility",
    category: "facility",
    highlight: false,
    description: "ร้านค้าสวัสดิการของวัด จำหน่ายเครื่องดื่ม ขนม ของใช้จำเป็น ดอกไม้ธูปเทียน และของที่ระลึก",
    openingHours: {
      allDay: { open: "08:00", close: "16:30" },
      note: "เปิดบริการทุกวัน",
    },
    gps: { lat: 15.33304896338545, lng: 100.07384697212439 },
    tips: null,
    photos: folderPhotosMap["ร้านค้าสวัสดิการ"] || [],
  },
  {
    id: 15,
    name: "ห้องสมุดประชาชนเฉลิมราชกุมารี",
    altName: "",
    shortName: "ห้องสมุดประชาชน",
    zone: "facility",
    category: "facility",
    highlight: false,
    description: "ห้องสมุดประชาชนเฉลิมราชกุมารี แหล่งค้นคว้าหนังสือธรรมะ ประวัติศาสตร์ และวรรณกรรมพระพุทธศาสนา",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดวันจันทร์ - เสาร์ (หยุดวันอาทิตย์)",
    },
    gps: { lat: 15.33117031546957, lng: 100.07429634345739 },
    tips: null,
    photos: folderPhotosMap["ห้องสมุดประชาชนเฉลิมราชกุมารี"] || [],
  },
  {
    id: 16,
    name: "อาคารที่พักผู้ปฏิบัติธรรมพระพินิจอักษร",
    altName: "",
    shortName: "ที่พักพระพินิจอักษร",
    zone: "facility",
    category: "facility",
    highlight: false,
    description: "อาคารที่พักสำหรับพุทธศาสนิกชนที่เดินทางมาบวชเนกขัมมะ เจริญพระกรรมฐาน และปฏิบัติธรรมค้างคืนที่วัด",
    openingHours: {
      allDay: { open: "08:00", close: "17:00" },
      note: "ติดต่อลงทะเบียนเข้าพักล่วงหน้า",
    },
    gps: { lat: 15.331304695601231, lng: 100.07396798705324 },
    tips: "ผู้เข้าพักต้องแต่งกายชุดขาว ปฏิบัติตามระเบียบของวัดอย่างเคร่งครัด",
    photos: folderPhotosMap["อาคารที่พักผู้ปฏิบัติธรรมพระพินิจอักษร"] || [],
  },
  {
    id: 17,
    name: "พระมหาวิหาร100ปี พระราชพรหมยาน (ศาลา 12 ไร่)",
    altName: "",
    shortName: "ศาลา 12 ไร่",
    zone: "wat-mai",
    category: "pavilion",
    highlight: true,
    description: "มหาวิหารขนาดใหญ่สร้างบนพื้นที่ 12 ไร่ ในวาระ 100 ปี ชาตกาล พระราชพรหมยาน ใช้สำหรับประกอบพิธีทำบุญใหญ่ ถวายสังฆทาน ปฏิบัติธรรม และงานบำเพ็ญกุศลสำคัญ",
    openingHours: {
      allDay: { open: "08:00", close: "17:00" },
      note: "เปิดสำหรับทำบุญ ถวายสังฆทาน และพิธีบุญใหญ่",
    },
    gps: { lat: 15.327797764473573, lng: 100.0702932934395 },
    tips: "เป็นจุดถวายสังฆทานใหญ่ และจุดนัดพบสำหรับงานพิธีสำคัญ",
    photos: folderPhotosMap["พระมหาวิหาร100ปี พระราชพรหมยาน (ศาลา 12 ไร่)"] || [],
  },
  {
    id: 18,
    name: "หอประชุมพระสุธรรมยานเถระ (โรงทานศาลา 4 ไร่)",
    altName: "",
    shortName: "หอประชุมพระสุธรรมยานเถระ",
    zone: "wat-mai",
    category: "pavilion",
    highlight: false,
    description: "หอประชุมเอนกประสงค์และสถานที่จัดโรงทานขนาดใหญ่ของวัด มีโรงทานจัดเลี้ยงอาหารแก่พุทธศาสนิกชนและผู้มาปฏิบัติธรรมในช่วงเทศกาลเข้าพรรษาและช่วงงานประจำปีของวัด",
    openingHours: {
      allDay: { open: "07:00", close: "17:00" },
      note: "มีโรงทานบริการในช่วงเข้าพรรษาและช่วงงานวัด",
    },
    gps: { lat: 15.3284, lng: 100.0707 },
    tips: "สถานที่จัดเลี้ยงโรงทานหลักของวัดช่วงเทศกาลงานบุญ",
    photos: folderPhotosMap["หอประชุมพระสุธรรมยานเถระ (โรงทานศาลา 4 ไร่)"] || [],
  },
  {
    id: 19,
    name: "โรงเรียนพระพินิจอักษร (ทองดี)",
    altName: "",
    shortName: "โรงเรียนพระพินิจอักษร",
    zone: "wat-mai",
    category: "facility",
    highlight: false,
    description: "โรงเรียนพระพินิจอักษร (ทองดี) สถานศึกษาที่ตั้งขึ้นเพื่อเป็นอนุสรณ์แด่พระพินิจอักษรและบรรพชน",
    openingHours: {
      allDay: { open: "08:00", close: "16:30" },
      note: "วันจันทร์ - ศุกร์ เวลาราชการ",
    },
    gps: { lat: 15.327498986050607, lng: 100.07096015524046 },
    tips: null,
    photos: folderPhotosMap["โรงเรียนพระพินิจอักษร (ทองดี)"] || [],
  },
  {
    id: 20,
    name: "พระอุโบสถ",
    altName: "",
    shortName: "พระอุโบสถ",
    zone: "wat-mai",
    category: "temple",
    highlight: true,
    description: "พระอุโบสถหลักฝั่งใหม่ สถานที่ประกอบสังฆกรรม อุปสมบท และพิธีกรรมทางศาสนา ตกแต่งอย่างวิจิตรบรรจง",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดให้เข้ากราบไหว้ทุกวัน กรุณาสำรวมกิริยา",
    },
    gps: { lat: 15.327888594011979, lng: 100.07124274985728 },
    tips: "จุดประกอบพิธีกรรมสำคัญของคณะสงฆ์วัดท่าซุง",
    photos: folderPhotosMap["พระอุโบสถ"] || [],
  },
  {
    id: 21,
    name: "ศาลาบูรพาจารย์",
    altName: "",
    shortName: "ศาลาบูรพาจารย์",
    zone: "wat-mai",
    category: "pavilion",
    highlight: false,
    description: "ศาลาประดิษฐานรูปหล่อบูรพาจารย์เพื่อรำลึกถึงพระคุณของบูรพมหากษัตริย์และพระเถราจารย์",
    openingHours: {
      allDay: { open: "08:00", close: "17:00" },
      note: "เปิดทุกวัน",
    },
    gps: { lat: 15.3283, lng: 100.0716 },
    tips: null,
    photos: folderPhotosMap["ศาลาบูรพาจารย์"] || [],
  },
  {
    id: 22,
    name: "ศาลานวราช (ติดต่อที่พัก)",
    altName: "",
    shortName: "ศาลานวราช",
    zone: "facility",
    category: "facility",
    highlight: false,
    description: "ศูนย์ติดต่อประสานงานและลงทะเบียนที่พักสำหรับผู้มาปฏิบัติธรรมรักษาศีลภายในวัดท่าซุง",
    openingHours: {
      allDay: { open: "08:00", close: "17:00" },
      note: "ติดต่อสอบถามและลงทะเบียนที่พักผู้ปฏิบัติธรรม",
    },
    gps: { lat: 15.327860573789454, lng: 100.07186750111678 },
    tips: "ผู้มาพักค้างปฏิบัติธรรมกรุณาติดต่อที่นี่ในเวลาทำการ",
    photos: folderPhotosMap["ศาลานวราช (ติดต่อที่พัก)"] || [],
  },
  {
    id: 23,
    name: "ศาลา 2 ไร่",
    altName: "",
    shortName: "ศาลา 2 ไร่",
    zone: "wat-mai",
    category: "pavilion",
    highlight: false,
    description: "ศาลาปฏิบัติธรรมและจัดกิจกรรมงานบุญ มีโรงทานจัดเลี้ยงอาหารแก่พุทธศาสนิกชนและผู้มาปฏิบัติธรรมในช่วงเทศกาลเข้าพรรษาและช่วงงานประจำปีของวัด",
    openingHours: {
      allDay: { open: "07:00", close: "17:00" },
      note: "มีโรงทานบริการในช่วงเข้าพรรษาและช่วงงานวัด",
    },
    gps: { lat: 15.32928370148598, lng: 100.07036608602283 },
    tips: "ร่วมกับศาลา 4 ไร่ จัดเป็นโรงทานใหญ่ของวัดท่าซุง",
    photos: folderPhotosMap["ศาลา 2 ไร่"] || [],
  },
  {
    id: 24,
    name: "ศาลา 3 ไร่",
    altName: "",
    shortName: "ศาลา 3 ไร่",
    zone: "wat-mai",
    category: "pavilion",
    highlight: false,
    description: "ศาลาอเนกประสงค์ขนาดใหญ่สำหรับรองรับสาธุชน นั่งสมาธิภาวนา และรับฟังพระธรรมเทศนา",
    openingHours: {
      allDay: { open: "08:00", close: "17:00" },
      note: "เปิดทุกวัน",
    },
    gps: { lat: 15.329175030730923, lng: 100.07109833169615 },
    tips: null,
    photos: folderPhotosMap["ศาลา 3 ไร่"] || [],
  },
  {
    id: 25,
    name: "อาคารธรรมวิโมกข์",
    altName: "",
    shortName: "อาคารธรรมวิโมกข์",
    zone: "wat-mai",
    category: "facility",
    highlight: false,
    description: "อาคารเผยแผ่พระธรรมคำสอน จัดพิมพ์และจำหน่ายหนังสือธรรมะ วารสารธรรมวิโมกข์ และเทปซีดีคำสอนของหลวงพ่อฤาษีลิงดำ",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดทำการทุกวัน",
    },
    gps: { lat: 15.33175, lng: 100.0728 },
    tips: "จุดค้นคว้าและบูชาหนังสือธรรมะคำสอนฉบับสมบูรณ์",
    photos: folderPhotosMap["อาคารธรรมวิโมกข์"] || [],
  },
  {
    id: 26,
    name: "อนุสาวรีย์พระเจ้าพรหมมหาราช",
    altName: "",
    shortName: "พระเจ้าพรหมมหาราช",
    zone: "wat-kao",
    category: "monument",
    highlight: false,
    description: "พระบรมราชานุสาวรีย์พระเจ้าพรหมมหาราช พระมหากษัตริย์ผู้ทรงกอบกู้แผ่นดินไทยในอดีต ซึ่งหลวงพ่อฤาษีลิงดำให้ความเคารพอย่างสูง",
    openingHours: {
      allDay: { open: "07:00", close: "18:00" },
      note: "ลานสักการะกลางแจ้ง เปิดทุกวัน",
    },
    gps: { lat: 15.3331, lng: 100.07455 },
    tips: "ตั้งอยู่ใกล้กับวิหารหลวงพ่อศักดิ์สิทธิ์ฝั่งวัดเดิม",
    photos: folderPhotosMap["อนุสาวรีย์พระเจ้าพรหมมหาราช"] || [],
  },
  {
    id: 27,
    name: "อาคารเสริมศรี",
    altName: "",
    shortName: "อาคารเสริมศรี",
    zone: "facility",
    category: "facility",
    highlight: false,
    description: "อาคารบริการและที่พักสำหรับคณะศรัทธาและผู้มาปฏิบัติธรรม",
    openingHours: {
      allDay: { open: "08:00", close: "17:00" },
      note: "เปิดทำการทุกวัน",
    },
    gps: { lat: 15.3315, lng: 100.07415 },
    tips: null,
    photos: folderPhotosMap["อาคารเสริมศรี"] || [],
  },
  {
    id: 28,
    name: "เจดีย์พุดตาน",
    altName: "",
    shortName: "เจดีย์พุดตาน",
    zone: "wat-kao",
    category: "monument",
    highlight: false,
    description: "เจดีย์โบราณทรงพุดตาน ศิลปะไทยผสมผสาน ตั้งอยู่คู่กับพระอุโบสถเก่าฝั่งวัดเดิม ทรงคุณค่าทางประวัติศาสตร์",
    openingHours: {
      allDay: { open: "08:00", close: "17:00" },
      note: "เปิดให้สักการะทุกวัน",
    },
    gps: { lat: 15.33365, lng: 100.07435 },
    tips: "ตั้งอยู่บริเวณลานรอบพระอุโบสถเก่าฝั่งวัดเดิม",
    photos: folderPhotosMap["เจดีย์พุดตาน"] || [],
  },
  {
    id: 29,
    name: "วิหารหลวงพ่อพระมหากัสสป",
    altName: "",
    shortName: "วิหารพระมหากัสสป",
    zone: "wat-kao",
    category: "vihara",
    highlight: false,
    description: "วิหารประดิษฐานรูปหล่อพระมหากัสสปเถระ พระมหาเถระผู้เป็นเลิศด้านธุดงควัตรในสมัยพุทธกาล และเป็นประธานปฐมสังคายนา",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดให้กราบไหว้ทุกวัน",
    },
    gps: { lat: 15.3334, lng: 100.0744 },
    tips: null,
    photos: folderPhotosMap["วิหารหลวงพ่อพระมหากัสสป"] || [],
  },
  {
    id: 30,
    name: "วิหารหลวงพ่อ 5 พระองค์",
    altName: "",
    shortName: "วิหาร 5 พระองค์",
    zone: "wat-kao",
    category: "vihara",
    highlight: true,
    description: "วิหารประดิษฐานพระพุทธรูปพระเจ้า 5 พระองค์ (พระกกุสันโธ พระโกนาคมโน พระกัสสโป พระสมณโคดม และพระศรีอาริยเมตไตรย)",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดให้กราบสักการะทุกวัน",
    },
    gps: { lat: 15.3341, lng: 100.07375 },
    tips: "กราบสักการะพระพุทธเจ้าทั้ง 5 พระองค์แห่งภัทรกัปป์",
    photos: folderPhotosMap["วิหารหลวงพ่อ 5 พระองค์"] || [],
  },
  {
    id: 31,
    name: "หอฉัน",
    altName: "",
    shortName: "หอฉัน",
    zone: "wat-kao",
    category: "facility",
    highlight: false,
    description: "โรงฉันภัตตาหารสำหรับพระภิกษุสงฆ์ และโรงทานฝั่งวัดเก่า",
    openingHours: {
      allDay: { open: "06:30", close: "13:00" },
      note: "ช่วงเช้าถึงบ่ายต้น",
    },
    gps: { lat: 15.33435, lng: 100.07355 },
    tips: null,
    photos: folderPhotosMap["หอฉัน"] || [],
  },
  {
    id: 32,
    name: "พระอุโบสถเก่า",
    altName: "",
    shortName: "โบสถ์เก่า",
    zone: "wat-kao",
    category: "temple",
    highlight: true,
    description: "โบสถ์โบราณดั้งเดิมของวัดท่าซุง สร้างขึ้นในสมัยกรุงศรีอยุธยาตอนปลาย ภายในมีจิตรกรรมฝาผนังอันทรงคุณค่าทางประวัติศาสตร์และศิลปกรรม",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดให้เข้าชมและสักการะทุกวัน",
    },
    gps: { lat: 15.33375, lng: 100.0741 },
    tips: "จุดชมภาพจิตรกรรมฝาผนังโบราณสมัยอยุธยาที่หาชมได้ยาก",
    photos: folderPhotosMap["พระอุโบสถเก่า"] || [],
  },
  {
    id: 33,
    name: "แพเลี้ยงปลา (วังมัจฉา)",
    altName: "",
    shortName: "แพเลี้ยงปลา",
    zone: "wat-kao",
    category: "facility",
    highlight: true,
    description: "แพริมแม่น้ำสะแกกรังสำหรับให้อาหารปลา ทำบุญปล่อยนกปล่อยปลา บรรยากาศร่มรื่น วิวแม่น้ำสะแกกรังอันเงียบสงบ มีฝูงปลาธรรมชาตินับหมื่นตัว",
    openingHours: {
      allDay: { open: "07:00", close: "17:30" },
      note: "เปิดทุกวัน มีจำหน่ายอาหารปลาและจุดปล่อยปลา",
    },
    gps: { lat: 15.33475, lng: 100.0748 },
    tips: "มีขนมปังและอาหารเม็ดจำหน่ายบนแพ ทำบุญให้อาหารปลาพร้อมชมวิถีชีวิตชาวแพสะแกกรัง",
    photos: folderPhotosMap["แพเลี้ยงปลา (วังมัจฉา)"] || [],
  },
  {
    id: 34,
    name: "มณฑปแก้วพระองค์ที่ 10 และ 11",
    altName: "",
    shortName: "มณฑปแก้วพระองค์ที่ 10-11",
    zone: "wat-kao",
    category: "vihara",
    highlight: false,
    description: "มณฑปประดับกระจกแก้ววิจิตรงดงาม ประดิษฐานพระพุทธรูปพระองค์ที่ 10 และ 11",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดให้สักการะทุกวัน",
    },
    gps: { lat: 15.33305, lng: 100.07445 },
    tips: null,
    photos: folderPhotosMap["มณฑปแก้วพระองค์ที่ 10 และ 11"] || [],
  },
  {
    id: 35,
    name: "มณฑปท้าวจาตุมหาราช",
    altName: "",
    shortName: "มณฑปท้าวมหาราช",
    zone: "wat-kao",
    category: "vihara",
    highlight: false,
    description: "มณฑปประดิษฐานรูปหล่อท้าวจาตุมหาราชทั้ง 4 พระองค์ (ท้าวเวสสุวรรณ ท้าวธตรฐ ท้าววิรุฬหก ท้าววิรูปักษ์) ผู้พิทักษ์ทิศทั้งสี่และคุ้มครองพระพุทธศาสนา",
    openingHours: {
      allDay: { open: "08:00", close: "17:00" },
      note: "เปิดให้สักการะทุกวัน",
    },
    gps: { lat: 15.33275, lng: 100.07465 },
    tips: "นิยมกราบไหว้ขอพรความปลอดภัย ปกป้องคุ้มครองจากภยันตรายและภูตผีปีศาจ",
    photos: folderPhotosMap["มณฑปท้าวจาตุมหาราช"] || [],
  },
  {
    id: 36,
    name: "วิหารหลวงพ่อศักดิ์สิทธิ์",
    altName: "",
    shortName: "วิหารหลวงพ่อศักดิ์สิทธิ์",
    zone: "wat-kao",
    category: "vihara",
    highlight: true,
    description: "วิหารประดิษฐานหลวงพ่อศักดิ์สิทธิ์ พระพุทธรูปโบราณเนื้อสำริด ปางมารวิชัย ศิลปะสมัยอยุธยา พระประธานคู่บารมีดั้งเดิมของวัดท่าซุง มีความศักดิ์สิทธิ์เลื่องลือด้านการบนบานขอพรสำเร็จ",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดให้กราบไหว้ทุกวัน",
    },
    gps: { lat: 15.33355, lng: 100.0742 },
    tips: "นิยมบนบานด้วยไข่ต้ม หัวหมู หรือบายศรีเมื่อสำเร็จสมปรารถนา",
    photos: folderPhotosMap["วิหารหลวงพ่อศักดิ์สิทธิ์"] || [],
  },
  {
    id: 37,
    name: "ตึกรับแขก (สถานที่จำหน่ายหนังสือ, คำสอน, วัตถุมงคล, ยาสมุนไพร)",
    altName: "",
    shortName: "ตึกรับแขก",
    zone: "wat-kao",
    category: "facility",
    highlight: false,
    description: "ศูนย์บริการของวัดฝั่งเดิม จำหน่ายหนังสือคำสอน ซีดีธรรมะ วัตถุมงคลแท้ของวัด และยาสมุนไพรตำรับหลวงพ่อฤาษีลิงดำ",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "เปิดทำการทุกวัน",
    },
    gps: { lat: 15.33235, lng: 100.07485 },
    tips: "จุดบูชาวัตถุมงคลและยาสมุนไพรแผนโบราณของวัดท่าซุง",
    photos: folderPhotosMap["ตึกรับแขก (สถานที่จำหน่ายหนังสือ, คำสอน, วัตถุมงคล, ยาสมุนไพร)"] || [],
  },
  {
    id: 38,
    name: "วิหารพระองค์ที่ 10 และ 11 ใต้ต้นโพธิ์",
    altName: "",
    shortName: "วิหารใต้ต้นโพธิ์",
    zone: "wat-kao",
    category: "vihara",
    highlight: false,
    description: "วิหารประดิษฐานพระองค์ที่ 10 และ 11 ภายใต้ร่มเงาของต้นพระศรีมหาโพธิ์อันศักดิ์สิทธิ์และร่มรื่น",
    openingHours: {
      allDay: { open: "08:00", close: "17:00" },
      note: "เปิดให้สักการะทุกวัน",
    },
    gps: { lat: 15.33325, lng: 100.07435 },
    tips: null,
    photos: folderPhotosMap["วิหารพระองค์ที่ 10 และ 11 ใต้ต้นโพธิ์"] || [],
  },
  {
    id: 39,
    name: "โรงเรียนพระสุธรรมยานเถระวิทยา",
    altName: "",
    shortName: "โรงเรียนพระสุธรรมยานฯ",
    zone: "facility",
    category: "facility",
    highlight: false,
    description: "โรงเรียนการกุศลของวัดในพระอุปถัมภ์ จัดการศึกษาแผนกสามัญและพระปริยัติธรรมแก่เยาวชน",
    openingHours: {
      allDay: { open: "08:00", close: "16:30" },
      note: "วันจันทร์ - ศุกร์ เวลาราชการ",
    },
    gps: { lat: 15.33182, lng: 100.07535 },
    tips: null,
    photos: folderPhotosMap["โรงเรียนพระสุธรรมยานเถระวิทยา"] || [],
  },
  {
    id: 40,
    name: "เรือคนึงหา (จามเทวีนาวา)",
    altName: "",
    shortName: "เรือคนึงหา",
    zone: "wat-kao",
    category: "facility",
    highlight: false,
    description: "เรือประวัติศาสตร์ของวัดท่าซุงสำหรับล่องแม่น้ำสะแกกรัง ชมทัศนียภาพวิถีชีวิตชาวแพและธรรมชาติริมสายน้ำอันสงบ",
    openingHours: {
      allDay: { open: "08:30", close: "16:30" },
      note: "ขึ้นอยู่กับตารางรอบเรือและระดับน้ำแม่น้ำสะแกกรัง",
    },
    gps: { lat: 15.3346, lng: 100.07505 },
    tips: "สามารถสอบถามรอบเรือได้ที่บริเวณแพปลาวังมัจฉา",
    photos: folderPhotosMap["เรือคนึงหา (จามเทวีนาวา)"] || [],
  },
];

console.log('Processed', places.length, 'places.');
fs.writeFileSync('scratch/full_40_places.json', JSON.stringify(places, null, 2), 'utf-8');
